# Generated by Django 6.0.3 on 2026-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniconlineapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medical_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
